### ISSUE TITLE
playerPhrase runtime variable 

### ISSUE THREAD

**Issue by alexhoffman-dev** [TellemBigAlsentya/tic-tac-toe-react#2]
Here is another example of maybe a core concept that I'm misunderstanding but given the issue with passing state down dynamically as props, I thought maybe I'd use a run time variable in GameBoard.js to define the active player phrase and pass it down as props depending on a win or draw scenario. 

Should I be instead passing current player and gameInProgress down as props so that player phrase can do its own logic and determine which phrase to display? Or should I have another state variable perhaps in GameBoard that keeps track of if the game is in progress, a win state or a draw state has been reached? 

I noticed that if I set the gameInProgress state of GameBoard to false manually using the React Dev tools, that the player phrase disappears completely, likely because when it's passed to PlayerPhrase, it is set as an empty string.

**Comment by Luke9389** [comment]
> given the issue with passing state down dynamically as props

I'm not sure what you're referring to here. Is it [this issue ](https://github.com/TellemBigAlsentya/tic-tac-toe-react/issues/1)you're talking about? 


Recommendations: 
1. Save the `playerUpPhrase` as state in `<GameBoard />`. Any time it needs to change, use the set function provided by `useState` to change it. 
2. Remove all logic from `<PlayerPhrase />`. The only prop it should take is the phrase it's supposed to display. This way it becomes a "dumb" component, who's only job is to display a string. Move all logic for generating the phrase into `<GameBoard />`.


Code Sample:
```js
// src/PlayerPhrase.js
import React from 'react';

export default function PlayerPhrase({phrase}) {
    return <h3>{ phrase }</h3>
};
```

This way, all of the logic for what gets displayed can be in the same place. You'll end up with a more simple system and less redundant checks/logic.
